sudo: required
dist: trusty
language: node_js
node_js:
  - '8'

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - ng build

script:
  - karma start karma.conf.js --single-run
  - ng build --prod

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: order-app-angular

notifications:
  email:
    on_failure: change
    on_success: change
